// <auto-generated />
using System;
using MentalHealthBlogAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MentalHealthBlog.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MentalHealthBlog.API.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentGivenById")
                        .HasColumnType("integer");

                    b.Property<int>("AssignmentGivenToId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentGivenById");

                    b.HasIndex("AssignmentGivenToId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("MentalHealthBlog.API.Models.Emotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Emotions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Indifferent(Bad)"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Apathetic(Bad)"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pressured(Bad)"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rushed(Bad)"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Overwhelmed(Bad)"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Out of control(Bad)"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Sleepy(Bad)"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Unfocused(Bad)"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Shocked(Surprised)"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Dismayed(Surprised)"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Disillusioned(Surprised)"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Perplexed(Surprised)"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Astonished(Surprised)"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Awe(Surprised)"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Eager(Surprised)"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Energetic(Surprised)"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Aroused(Happy)"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Cheeky(Happy)"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Free(Happy)"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Joyful(Happy)"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Curious(Happy)"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Inquisitive(Happy)"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Successful(Happy)"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Confident(Happy)"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Respected(Happy)"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Valued(Happy)"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Courageous(Happy)"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Creative(Happy)"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Loving(Happy)"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Thankful(Happy)"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Sensitive(Happy)"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Intimate(Happy)"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Hopeful(Happy)"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Inspired(Happy)"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Betrayed(Angry)"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Resentful(Angry)"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Disrespected(Angry)"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Ridiculed(Angry)"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Indignant(Angry)"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Violated(Angry)"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Furious(Angry)"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Jealous(Angry)"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Provoked(Angry)"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Hostile(Angry)"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Infuriated(Angry)"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Annoyed(Angry)"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Withdrawn(Angry)"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Numb(Angry)"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Skeptical(Angry)"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Dismissive(Angry)"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Isolated(Sad)"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Abandoned(Sad)"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Victimized(Sad)"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Fragile(Sad)"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Grief(Sad)"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Powerless(Sad)"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Ashamed(Sad)"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Remorseful(Sad)"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Empty(Sad)"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Inferior(Sad)"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Disappointed(Sad)"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Embarrassed(Sad)"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Judgmental(Disgusted)"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Embarrassed(Disgusted)"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Appalled(Disgusted)"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Revolted(Disgusted)"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Nauseated(Disgusted)"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Detestable(Disgusted)"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Horrified(Disgusted)"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Hesitant(Disgusted)"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Helpless(Fearful)"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Frightened(Fearful)"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Overwhelmed(Fearful)"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Worried(Fearful)"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Inadequate(Fearful)"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Inferior(Fearful)"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Worthless(Fearful)"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Insignificant(Fearful)"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Excluded(Fearful)"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Persecuted(Fearful)"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Nervous(Fearful)"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Exposed(Fearful)"
                        });
                });

            modelBuilder.Entity("MentalHealthBlog.API.Models.MentalHealthExpert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRejected")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("PhotoAsFile")
                        .HasColumnType("bytea");

                    b.Property<string>("PhotoAsPath")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MentalHealthExperts");
                });

            modelBuilder.Entity("MentalHealthBlog.API.Models.PostEmotion", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<int>("EmotionId")
                        .HasColumnType("integer");

                    b.HasKey("PostId", "EmotionId");

                    b.HasIndex("EmotionId");

                    b.ToTable("PostsEmotions");
                });

            modelBuilder.Entity("MentalHealthBlog.API.Models.PostTag", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("PostId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PostsTags");
                });

            modelBuilder.Entity("MentalHealthBlog.API.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("MentalHealthBlog.API.Models.RegularUser", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("RegularUsers");
                });

            modelBuilder.Entity("MentalHealthBlog.API.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Parent"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Psychologist / Psychotherapist"
                        });
                });

            modelBuilder.Entity("MentalHealthBlog.API.Models.Share", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsKeepingContent")
                        .HasColumnType("boolean");

                    b.Property<string>("ShareGuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SharedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SharedPostId")
                        .HasColumnType("integer");

                    b.Property<int?>("SharedWithId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SharedPostId");

                    b.HasIndex("SharedWithId");

                    b.ToTable("Shares");
                });

            modelBuilder.Entity("MentalHealthBlog.API.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ljubav"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Porodica"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Posao"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Zdravlje"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Prijatelji"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Karijera"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Novac"
                        });
                });

            modelBuilder.Entity("MentalHealthBlog.API.Models.TherapyRequest", b =>
                {
                    b.Property<int>("RegularUserId")
                        .HasColumnType("integer");

                    b.Property<int>("MentalHealthExpertId")
                        .HasColumnType("integer");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RegularUserId", "MentalHealthExpertId");

                    b.ToTable("TherapyRequests");
                });

            modelBuilder.Entity("MentalHealthBlog.API.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("MentalHealthBlogAPI.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("MentalHealthBlogAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MentalHealthBlog.API.Models.Assignment", b =>
                {
                    b.HasOne("MentalHealthBlog.API.Models.MentalHealthExpert", "AssignmentGivenBy")
                        .WithMany()
                        .HasForeignKey("AssignmentGivenById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MentalHealthBlogAPI.Models.User", "AssignmentGivenTo")
                        .WithMany()
                        .HasForeignKey("AssignmentGivenToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignmentGivenBy");

                    b.Navigation("AssignmentGivenTo");
                });

            modelBuilder.Entity("MentalHealthBlog.API.Models.PostEmotion", b =>
                {
                    b.HasOne("MentalHealthBlog.API.Models.Emotion", "Emotion")
                        .WithMany()
                        .HasForeignKey("EmotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MentalHealthBlogAPI.Models.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emotion");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("MentalHealthBlog.API.Models.PostTag", b =>
                {
                    b.HasOne("MentalHealthBlogAPI.Models.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MentalHealthBlog.API.Models.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MentalHealthBlog.API.Models.RefreshToken", b =>
                {
                    b.HasOne("MentalHealthBlogAPI.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MentalHealthBlog.API.Models.RegularUser", b =>
                {
                    b.HasOne("MentalHealthBlogAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MentalHealthBlog.API.Models.Share", b =>
                {
                    b.HasOne("MentalHealthBlogAPI.Models.Post", "SharedPost")
                        .WithMany()
                        .HasForeignKey("SharedPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MentalHealthBlog.API.Models.MentalHealthExpert", "SharedWith")
                        .WithMany()
                        .HasForeignKey("SharedWithId");

                    b.Navigation("SharedPost");

                    b.Navigation("SharedWith");
                });

            modelBuilder.Entity("MentalHealthBlog.API.Models.TherapyRequest", b =>
                {
                    b.HasOne("MentalHealthBlog.API.Models.RegularUser", "RegularUser")
                        .WithMany()
                        .HasForeignKey("RegularUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegularUser");
                });

            modelBuilder.Entity("MentalHealthBlog.API.Models.UserRole", b =>
                {
                    b.HasOne("MentalHealthBlog.API.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MentalHealthBlogAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MentalHealthBlogAPI.Models.Post", b =>
                {
                    b.HasOne("MentalHealthBlogAPI.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MentalHealthBlogAPI.Models.User", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
